name: artofyoshi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8081575587857515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#37499f'
    - '#fdcf08'
    - '#b6d3e1'
    - '#ffffff'
    - '#b49507'
  brandStrength: 0.10764957638457417
  lightness: 0.25
  saturation: 0.3213861172553152
  rhythmicContrast: 0.5
purpose: []
